config/routes.rb
SimpleApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }

  validates :name, presence: true,
                  length: { maximum: 50 }
                  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a> by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer> 

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "sample app", '#', id: "logo" %>
        <nav>
          <ul class="nav pull-right">
            <li><%= link_to "Home",     root_path %></li>
            <li><%= link_to "Help",     help_path %></li>
            <li><%= link_to "Sign in",  signin_path %></li>
          </ul>
        </nav>
      </div>
    </div>
  </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <% render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>

</body>
</html>

app/views/shared/_error_messages.html.haml
= if @user.errors.any?
  %div{id: "error_explanation"}
    %div{class: "alert alert-error"}
      The form contains #{pluralize(@user.errors.count, "error")}
    %ul
      =@user.errors.full_messages.each do |msg|
        %li 
          * #{msg}

app/views/static_pages/about.html.haml
- content_for(:title, "About Us")

!!!
%html
  %head
  %body
    %h1 About Us
    %p
      The
      = link_to 'Ruby on Rails Tutorial', 'blabla'
      is a project to make a book and screencasts to teach web development with
      = succeed "." do
        = link_to 'Ruby on Rails', 'cos tam'
      This is the sample application for the tutorial.

app/views/static_pages/contact.html.haml
- content_for(:title, "Contact")

!!!
%html
  %head
  %body
    %h1 Contact
    %p 
      Contact Ruby on Rails Tutorial about the sample app at the
      = link_to "content page", 'http://railstutorial.org/contact'

app/views/static_pages/help.html.haml
- content_for(:title, "Help")

!!!
%html
  %head
  %body
    %h1 Help
    %p
      Get help on the Ruby on Rails Tutorial at the
      = link_to 'Rails Tutorial help page', 'http://railstutorial.org/help'
      To get help on this sample app, see the
      = link_to 'Rails Tutorial book', 'static_pages/help'

app/views/static_pages/home.html.haml
.center.hero-unit
  %h1 Welcome to the Sample App
  %h2
    This is the home page for the 
    = link_to 'Ruby on Rails Tutorial', 'http://blabla.org'
    sample application.
  = link_to "Sign up now!", signup_path, :class => "btn btn-large btn-primary"

app/views/users/new.html.haml
- content_for(:title, 'Sign up')

%h1 Sign up
%div{class: "row"}
  %div{class: "span6 offset3"}
    = form_for @user do |f|
      
      = render 'shared/error_messages'
      
      = f.label :name
      = f.text_field :name
      
      = f.label :email
      = f.text_field :email
      
      = f.label :password
      = f.password_field :password
      
      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation
      
      = f.submit "Create my account", class: "btn btn-large btn-primary"

app/views/users/show.html.haml
- content_for(:title, @user.name)

%div{class: "row"}
  %aside{class: "span4"}
    %section
      %h1
        = gravatar_for @user
        #{@user.name}